closure fix
allure-framework/allure-codeception pull request #110
Opened 2023-01-23 07:52 UTC by alnivv-vi

fix error for executeInSelenium function (Closure as argument)

2023-01-23 07:52 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/allure-framework/allure-codeception?pullRequest=110) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/allure-framework/allure-codeception?pullRequest=110) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/allure-framework/allure-codeception?pullRequest=110) it.</sub>

2023-01-26 09:34 UTC, baev commented
@alnivv-vi, thanks for the PR. Could you please fix the build?

2023-01-26 10:33 UTC, alnivv-vi commented
@baev [check](https://github.com/allure-framework/allure-codeception/actions/runs/4014274373) please

2023-03-22 09:09 UTC, baev requested changes

2023-03-22 09:09 UTC, baev commented on src/Internal/ArgumentAsString.php
> +        return (string)new self($argument);
revert

2023-03-22 09:09 UTC, baev commented on src/Internal/ArgumentAsString.php
> +            return (string)$argument;
revert

2023-03-27 06:51 UTC, merged

2023-03-27 06:51 UTC, baev commented
@alnivv-vi thanks!